# Change these first
owner: Cybertheory # Your GitHub organization or username, where this repository lives
repo: PikfarmStatus # The name of this repository

sites:
  - name: Pikfarm.com
    url: https://www.pikfarm.com
  - name: Pik.farm
    url: https://pik.farm
  - name: Newsletter
    url: https://news.pik.farm/sign-up
  - name: Blog
    url: https://blog.pik.farm

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.pik.farm
  theme: dark
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/cybertheory/PikfarmStatus/master/assets/APP%20Icon%20v2.0.svg
  name: Pikfarm Status Dashboard
  introTitle: "Pikfarm is the first P2P produce marketplace."
  introMessage: This is the Pikfarm Status Dashboard which uses **real-time** data from our [GitHub repository](https://github.com/cybertheory/PikfarmStatus).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
